# Generated by Django 3.1 on 2022-05-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_users_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wishlist',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
