# Generated by Django 3.1 on 2022-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_is_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
