# Generated by Django 3.1 on 2022-02-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220220_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to='userprofile'),
        ),
    ]
